# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI with Ant

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: [ self-hosted ]

    steps:
    # - uses: actions/checkout@v4
    # - name: Set up JDK 
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '21'
    #     distribution: 'temurin'
    - name: poc1
      run: Write-Output $env:PATH
    - name: poc1a
      run: Write-Output $env
    - name: poc2
      run: java -version
    # - name: Build with Ant
    #   run: ant -noinput -buildfile build.xml
