# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI with Ant

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: [ self-hosted ]

    steps:
    # - uses: actions/checkout@v4
    # - name: Set up JDK 
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '21'
    #     distribution: 'temurin'
    - name: poc1
      run: |
        Write-Output $env:PATH
        Write-Output $env
        Write-Output $GITHUB_WORKSPACE
        Write-Output $GITHUB_REPOSITORY
        Write-Output $GITHUB_REPOSITORY_OWNER
    - name: poc2
      run: |
        java -version
        mvn -v
    - name: mount drive
      ## net use may give an error
      continue-on-error: true
      run: |
        net use U: \\VBOXSVR\proj.HKICL-CMUNP /persistent:no
    - name: poc3
      run: |
        dir u:\
        dir        
    - name: cleanup
      run: |
        rm -Recurse ${{github.workspace}}\*
        dir
    # - name: checkout
    #   uses: actions/checkout@v4
    #   with:
    #     repository: u:\proj.HKICL-CMUNP.src\iclcmu_scp
    # - name: checkout-self
    #   uses: actions/checkout@v4
    #   with: 
    #     path: ''
    - name: checkout2
      run: |
        git config --global --add safe.directory "*"
        git clone u:\proj.HKICL-CMUNP.src\iclcmu_scp
        dir
        
    # - name: Build with Ant
    #   run: ant -noinput -buildfile build.xml
